[dependencies]
  light = {git = "https://gitcode.com/service/light.git", branch = "main", version = "0.0.1"}
  jorm = {git = "https://gitcode.com/service/jorm.git", branch = "main", version = "0.0.1"}
  mysql = {git = "https://gitcode.com/service/cangjie-mysql-driver.git", branch = "main", version = "0.0.1"}
  
[package]
  cjc-version = "0.55.3"
  compile-option = "-Woff unused"
  description = "nothing here"
  link-option = ""
  name = "fires"
  output-type = "executable"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  [package.package-configuration]
